
[build]
  command = "npm run build"
  publish = "dist/public"


[[redirects]]
  from = "/api/restaurants/1/*"
  to = "/api/restaurants/1/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
